env:
  browser: true
  es6: true
  webextensions: true
plugins:
  - import
extends:
  - eslint:recommended
  #- plugin:import/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:

  # Style
  indent:
    - warn
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-var: error
  no-sequences: error

  # Additional control
  import/no-cycle: error
  import/first: error
  # Would be nice to enforce order, but after resolution they are all relative
  #import/order:
  #  - warn
  #  - newlines-between: never

  # Allowed
  no-console: off

settings:
  import/resolver:
    babel-root-slash-import:
      debug: false
